In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.interpolate
import scipy.integrate

For a population uniform on the values $y_i$, i = 1 to n, indexed in non-decreasing order $(y_i ≤ y_{i+1})$:

$$G={\frac {2\Sigma _{i=1}^{n}\;iy_{i}}{n\Sigma _{i=1}^{n}y_{i}}}-{\frac {n+1}{n}}$$

avec: n: length of samples = len(actual)

In [12]:
pred = [0.9, 0.3, 0.8, 0.75, 0.65, 0.6, 0.78, 0.7, 0.05, 0.4, 0.4, 0.05, 0.5, 0.1, 0.1]
actual = [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [20]:
all = np.asarray(np.c_[actual, pred, np.arange(len(actual))], dtype=np.float)

In [17]:
all

array([[  1.  ,   0.9 ,   0.  ],
       [  1.  ,   0.3 ,   1.  ],
       [  1.  ,   0.8 ,   2.  ],
       [  1.  ,   0.75,   3.  ],
       [  1.  ,   0.65,   4.  ],
       [  1.  ,   0.6 ,   5.  ],
       [  0.  ,   0.78,   6.  ],
       [  0.  ,   0.7 ,   7.  ],
       [  0.  ,   0.05,   8.  ],
       [  0.  ,   0.4 ,   9.  ],
       [  0.  ,   0.4 ,  10.  ],
       [  0.  ,   0.05,  11.  ],
       [  0.  ,   0.5 ,  12.  ],
       [  0.  ,   0.1 ,  13.  ],
       [  0.  ,   0.1 ,  14.  ]])

In [25]:
np.lexsort((all[:, 2], -1 * all[:, 1]))

array([ 0,  2,  6,  3,  7,  4,  5, 12,  9, 10,  1, 13, 14,  8, 11], dtype=int64)

In [26]:
all = all[np.lexsort((all[:, 2], -1 * all[:, 1]))]

In [27]:
all

array([[  1.  ,   0.9 ,   0.  ],
       [  1.  ,   0.8 ,   2.  ],
       [  0.  ,   0.78,   6.  ],
       [  1.  ,   0.75,   3.  ],
       [  0.  ,   0.7 ,   7.  ],
       [  1.  ,   0.65,   4.  ],
       [  1.  ,   0.6 ,   5.  ],
       [  0.  ,   0.5 ,  12.  ],
       [  0.  ,   0.4 ,   9.  ],
       [  0.  ,   0.4 ,  10.  ],
       [  1.  ,   0.3 ,   1.  ],
       [  0.  ,   0.1 ,  13.  ],
       [  0.  ,   0.1 ,  14.  ],
       [  0.  ,   0.05,   8.  ],
       [  0.  ,   0.05,  11.  ]])

In [28]:
totalLosses = all[:, 0].sum()

In [32]:
all[:, 0].cumsum().sum()

65.0

In [33]:
def gini(actual, pred):
    #check len(actual) == len(predictions), if not return error
    assert (len(actual) == len(pred))
    #create array of real observations and predictions and index
    all = np.asarray(np.c_[actual, pred, np.arange(len(actual))], dtype=np.float)
    #sort following order deacresing of predictions
    all = all[np.lexsort((all[:, 2], -1 * all[:, 1]))]
    totalLosses = all[:, 0].sum()
    giniSum = 2 * all[:, 0].cumsum().sum() / totalLosses

    giniSum -= (len(actual) + 1) 
    return giniSum / len(actual)

In [34]:
def gini_normalized(actual, pred):
    return gini(actual, pred) / gini(actual, actual)

In [35]:
gini_normalized(actual, pred)

0.62962962962962987

In [36]:
gini(actual, pred)

0.37777777777777788